/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,js,ts,jsx,tsx}",
  "./components/**/*.{html,js,ts,jsx,tsx}",
  "./node_modules/flowbite-react/**/*.js"],
  theme: {
    extend: {
      colors: {
        brandprimary: "var(--brandprimary)",
        building: "var(--building)",
        "default-white": "var(--default-white)",
        landcover: "var(--landcover)",
        neutraldgrey: "var(--neutraldgrey)",
        neutralsilver: "var(--neutralsilver)",
        neutralwhite: "var(--neutralwhite)",
        roadnetwork: "var(--roadnetwork)",
        "roadnetwork-casing": "var(--roadnetwork-casing)",
        roadpath: "var(--roadpath)",
        stadium: "var(--stadium)",
        "text-gray-900": "var(--text-gray-900)",
        tunnel: "var(--tunnel)",
        "tunnel-casing": "var(--tunnel-casing)",
        tunnelpath: "var(--tunnelpath)",
        "variable-collection-blue-secondary": "var(--variable-collection-blue-secondary)",
        "variable-collection-dark-blue": "var(--variable-collection-dark-blue)",
        "variable-collection-dark-green": "var(--variable-collection-dark-green)",
        "variable-collection-light-blue": "var(--variable-collection-light-blue)",
        primary: {"50":"#eff6ff","100":"#dbeafe","200":"#bfdbfe","300":"#93c5fd","400":"#60a5fa","500":"#3b82f6","600":"#2563eb","700":"#1d4ed8","800":"#1e40af","900":"#1e3a8a","950":"#172554"}
      },
      fontFamily: {
        "body-regular-body-2": "var(--body-regular-body-2-font-family)",
        "button-link-medium": "var(--button-link-medium-font-family)",
        "heading-headline-2": "var(--heading-headline-2-font-family)",
        road: "var(--road-font-family)",
        'body': [
          'Inter', 
          'ui-sans-serif', 
          'system-ui', 
          '-apple-system', 
          'system-ui', 
          'Segoe UI', 
          'Roboto', 
          'Helvetica Neue', 
          'Arial', 
          'Noto Sans', 
          'sans-serif', 
          'Apple Color Emoji', 
          'Segoe UI Emoji', 
          'Segoe UI Symbol', 
          'Noto Color Emoji'
        ],
        'sans': [
      'Inter', 
      'ui-sans-serif', 
      'system-ui', 
      '-apple-system', 
      'system-ui', 
      'Segoe UI', 
      'Roboto', 
      'Helvetica Neue', 
      'Arial', 
      'Noto Sans', 
      'sans-serif', 
      'Apple Color Emoji', 
      'Segoe UI Emoji', 
      'Segoe UI Symbol', 
      'Noto Color Emoji'
    ]      
      },
    },
  },
  plugins: [
    require('flowbite/plugin'),
  ],
};
